# Generated by Django 6.0.5 on 2026-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('media', models.FloatField()),
                ('faltas', models.IntegerField()),
            ],
        ),
    ]
